- .github/CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
Add initial maintainers and fix some language
> Add initial maintainers and fix some language

- _layouts/default.html
Adds commands menu item to top navigation
n/a
> adds commands to top nav

- _layouts/default.html
> [Move to Prod] Commands in top nav to prod

- .github/CODEOWNERS
Enable @stockholmux to approve PRs 
n/a
> Adds stockholmux to codeowners

- .github/CODEOWNERS
- .github/workflows/deply.yml
- .gitignore
- _includes/docs
- _layouts/default.html
- _layouts/doc-import.html
- about/index.html
- about/index.md
- docs/management/persistence.md
> Move to Prod: About page & persistence

- connect.md
Adds a list of ways you can connect with Valkey
#32 
> Adds basic connect/contact page

- about/index.md
Marking formatting fix for about page.  
n/a
> Fix formatting: one line per sentence

- _includes/release.html
- _releases/v7-2-4-rc1.markdown
On the downloads/release page:
Refinements:
The docker/container section by allowing multiple registries in the future, adds a link to the registry page, and gives a simple example of how to use it with docker.
Additions:
Adds package managers for linux distros and platforms. This allows for package names, links to package pages, and leaves room for examples in the future.
For the 7.2.4-rc1 release this PR:
- modifies the existing front matter to support the new template
- Adds Fedora and EPEL packages
n/a
> downloads/release: enhance docker, add package managers

- Dockerfile
- README.md
- docker-gemfile.sh
Adding a Dockerfile to enable testing across various devices without having to install anything locally. README.md updated accordingly
> Adding Dockerfile, script, and instructions to README

- _data/repos.yml
- _layouts/homepage.html
- _sass/_valkey.scss
- index.markdown
- Adds feature repos to side bar
- Fixes misc issues with formatting and duplication
- Adds temporary lorem ipsum for content measurement (to be replace by subsequent PR)
n/a
> Homepage update

- _includes/release.html
- _releases/v7-2-5.markdown
Adds binary artifacts to release page. 
> v7.2.5 binaries

- README.md
- Removes inaccurate information (old staging website).
- Adds info about submodules
- Adds info about Ruby versions
Fixes #42
> updates readme to remove out-of-date info

- index.markdown
Change to preferred lua caps 
#54 
> fix lua caps

- _includes/docs
- _includes/topics
- docs/index.md
- docs/topics/acl.md
- docs/topics/keyspace.md
- docs/topics/persistence.md
1. Updates the docs submodule
2. changes the structure to reflect the flat `/topic/...` structure adopted in valkey-io/valkey-doc#61
n/a
> Update doc urls

- index.markdown
Fixes a few typos located on the homepage.
#64 
> Fixes typos on the homepage

- README.md
Adds note to README to avoid misplaced work.
n/a
> adds note about SSG transition

- .github/workflows/zola-deploy.yml
This is a github action that builds the zola version of the website. This is a stepping stone to the deployment script.
#11 
> Deployment GitHub action for zola version

- CONTRIBUTING-BLOG-POST.md
- CONTRIBUTING.md
- SECURITY.md
This PR cleans up the `CONTRIBUTING.md` file, adds a `SECURITY.md` and a `CONTRIBUTING-BLOG-POST.md` file to describe how to contribute blog content to the website.
n/a
> Contributing updates and guide for writing a blog post

- content/blog/whats-new-june-2024.md
- templates/shortcodes/youtube.html
A start to the what's new post for June 2024.
To be published on June 27.
(This also adds a [youtube embedding shortcode suggested from  Zola documentation](https://www.getzola.org/documentation/content/shortcodes/#youtube))
n/a
> What's new post for 2024-06

- config.toml
Add title metadata to Zola. This helps generating Atom feed with proper title, instead of leaving it blank.
Closes #96 
> adds title to config.toml

- content/blog/2024-06-27-using-bitnami-valkey-chart/index.md
This schedules the Bitnami post (#91) with the correct date
n/a
> corrects bitnami blog post publish date

- content/download/releases/v7-2-6.md
Updating the downloads page with 7.2.6 version artifact links
NA
> Updating the downloads page with 7.2.6 version

- templates/default.html
Update the footer to include the updated privacy and trademark policy provided by the LF.
No related issue. 
> Update footer to include updated trademark and privacy policy

- .github/ISSUE_TEMPLATE/add_participant_form_template.md
- .github/ISSUE_TEMPLATE/add_partner_form_template.md
As discussed online, this is a template that could be used to create something similar to a form to add new partners to the website.
> Add template for adding a partner

- .github/ISSUE_TEMPLATE/add_participant_form_template.md
- templates/includes/head.html
This PR pushes the analytics PR #111 into prod.
n/a
> Push to Prod: Analytics

- templates/default.html
Updates the footer to include a terms of use and a link to the other LF projects policies (this update is based on guidance from LF) 
#13 
> Footer update for policies

- content/blog/2024-09-16-valkey-8-ga.md
Adds a blog post for Valkey 8 being GA. To remain in draft status until GA is ready and after the downloads page is ready.
n/a
> Valkey 8 GA blog

- config.toml
Removes the note about Valkey Developer Day and adds a banner about valkey 8
n/a
> Adds banner about valkey 8

- config.toml
- content/blog/2024-09-16-valkey-8-ga.md
- content/download/releases/v7-2-7.md
- content/download/releases/v8-0-1.md
- templates/release-section.html
Moves to production two patch release 7.2.7, 8.0.1 and accompanying notes and template update
n/a 
> move to prod: Patch release 7.2.7 and 8.0.1

- content/connect.md
We've had the Matrix chat for quite some time, but we have not really told anyone about it, which has made the usage of it quite low.
Hopefully this helps advertise that we do have a chat for those who want it.
N/A
> content/connect: Add the Matrix chat

- templates/author-page.html
Adds tempalte for author's pages.
Closes #137 
> adds real styling/template for authors pages

- .gitignore
- build/init-commands.sh
- sass/_valkey.scss
- templates/commands.html
- templates/default.html
This moves command categorization to production 
#150
> Move to Prod: Categorized Commands

- content/download/releases/v7-2-8.md
- content/download/releases/v8-0-2.md
Add new metadata for 7.2.8 and 8.0.2 release
None
> Update the website with 7.2.8 and 8.0.2

- templates/command-page.html
> Gracefully handle missining resp2 and resp3 responses

- README.md
Fix incorrect link to valkey-io/valkey repo.
> Fix incorrect link to valkey-io/valkey repo.

- content/blog/2024-12-20-2024-year-of-valkey/index.md
> Correct spelling of Verizon

- content/blog/2024-06-27-using-bitnami-valkey-chart/index.md
> Remove duplicated "the"

- CONTRIBUTING-BLOG-POST.md
- Fixes two issues from prod push review
- Fixes one proof reading miss.
n/a
> Blog post guidance update

- README.md
> Document the source of command replies in the README

- content/blog/2025-03-4-go-client-in-public-preview.md
Updated contributors section for go client public preview announcement 
> Updated contributors section for go client public preview announcement

- templates/valkey-website-template.md
This PR contains a template for the releases section of the Valkey website. This will be used in valkey-release-automation repository in order to automate the release section of the website.
> Adding the template for the releases section of the Valkey website

- sass/_valkey.scss
- static/assets/js/nav.js
- static/img/valkey-horizontal.svg
- templates/default.html
- templates/includes/head.html
- Add mobile-friendly navigation with hamburger menu
- Style dropdown menus for desktop and mobile views
- Include New Valkey logo in header
- Add navigation menu logic in dedicated nav.js file
> feat(ui): restyle top nav and implement responsive navigation with mobile menu

- content/download/releases/v7-2-9.md
This pull request updates the downloads page of the valkey website with the new release 7.2.9.
> Update website for version 7.2.9

- content/download/releases/v8-0-3.md
This pull request updates the downloads page of the valkey website with the new release 8.0.3.
> Update website for version 8.0.3

- content/download/releases/v8-1-1.md
This pull request updates the downloads page of the valkey website with the new release 8.1.1.
> Update website for version 8.1.1

- content/download/releases/v8-1-2.md
This pull request updates the downloads page of the valkey website with the new release 8.1.2.
> Update website for version 8.1.2

- config.toml
> adds bundle banner

- content/download/releases/v8-0-4.md
This pull request updates the downloads page of the valkey website with the new release 8.0.4.
> Update website for version 8.0.4

- content/download/releases/v7-2-10.md
This pull request updates the downloads page of the valkey website with the new release 7.2.10.
> Update website for version 7.2.10

- content/blog/2025-07-10-keyspace-save-the-date.md
Adds a blog post about the upcoming Valkey conference.
n/a
> adds blog post for Keyspace save the date

- sass/_valkey.scss
- templates/participants.html
refactor: remove participants right banner image
> refactor: remove participants right banner image

- content/blog/2025-07-10-keyspace-save-the-date.md
We extended the CFP date slightly so updating the blog post with current information. 
n/a
> Update cfp date

- content/blog/2025-08-12-keyspace-schedule.md
- content/events/keyspace-2025/index.md
Adds blog post about the keyspace schedule and updates the keyspace landing page.
n/a
> Schedule update keyspace 2025

- content/download/releases/v8-0-5.md
This pull request updates the downloads page of the valkey website with the new release 8.0.5.
> Update website for version 8.0.5

- content/events/keyspace-2025/index.md
The missing two slide decks came in for the event page. This PR adds them in.
n/a
> adds final two slide decks to keyspace 2025

- content/download/releases/v8-1-4.md
This pull request updates the downloads page of the valkey website with the new release 8.1.4.
> Update website for version 8.1.4

- content/community/pyconafrica2025.md
This landing page will live at: https://valkey.io/community/pyconafrica2025/ and will direct attendees to conference materials.
n/a
> Adds community landing page for PyCon Africa 2025
