CODE_OF_CONDUCT.md, _layouts/homepage.html, index.markdown
- Removes some non-relevant template cruft
- Moves CoC from dummy text to Contributor Covenant to match valkey-io/valkey
n/a
=> removing cruft; switch CoC to match valkey-io/valkey

404.markdown, _includes/head.html, _layouts/default.html, about/index.html, download/index.html, index.markdown, source.markdown
1. Removed various bits of template leftovers (footer links, homepage dummy text, 404 page references)
2. Commented out google analytics heading, this seems like another template left over. I assume LF will want to have their own tags in this area.
3. Added stub pages for `about` and `download` so they don't 404
n/a
=> Additional template clean up

_sass/_colors.scss, _sass/_valkey.scss
Removes remaining blues and serif fonts, makes the site more neutral
#14
=> clean up brand, make it look like the LF announcement 

.github/workflows/deply.yml, .gitignore, _includes/docs, _layouts/doc-import.html, docs/management/persistence.md
- Adds doc import layout (see below)
- Adds example of using doc import layout for `docs/management/persistence.md`
- Adds another symbolic link to the `_includes` folder for the markdown docs from `valkey-doc` in the workflow
- Updates submodule
This allows the consumption of the existing markdown files in `valkey-doc` by stripping out the existing frontmatter (which is not relevant). Alternately, if there isn't front matter on the file (it doesn't start with `---`) it still works.
This way we can keep the concerns separated: `valkey-doc` contains content, `valkey-website` contains metadata and site specific (templates, forward, etc.) information. 
n/a
=> Add the ability to pull in docs from `valkey-doc`

_config.yml, _includes/release.html, _layouts/release.html, _releases/v7-2-4-rc1.markdown, download/index.html
Adds a basic downloads page and release mechanism. 
- Each release gets a markdown file in `/_releases/`
- So, for `v7.2.4-rc1` there is `_releases/v7-2-4-rc1.markdown`
- The front matter of the markdown file defines the metadata regarding the release
- `/download/` is populated by the most recent `_release` file (by `date` in front matter) 
- Each release gets a stable link at `/download/releases/` So, for `v7.2.4-rc1` it will be `/download/releases/v7-2-4-rc1/`
(This only contains github tag and docker release, but can be easily expanded)
Related to #13
=> adds basic downloads page

docs/index.md, docs/management/security/acl.md, docs/manual/keyspace-notifications.md
- Adds a non-dynamic docs page
- Adds ACL and  Keyspace notifications docs page metadata
Right now docs are swiss cheese as the team works through "localizing" everything to Valkey. It would be very frustrating to see nested menu after nested menu with single items on them. Once the docs are fleshed out, it would be smart to move to a dynamic display that iterates over pages.
Related to #13 
=> Docs stub page + 2 docs pages

docs/index.md
GitHub Pages hosting doesn't have the ability to do URLs that end in `/` for individual HTML files. So, for example, 
`https://valkey-io.github.io/docs/management/persistence/` won't resolve `https://valkey-io.github.io/docs/management/persistence.html`.
This PR changes the links on docs index to direct `.html` files instead.
=> change links to direct file vs path

_posts/2024-04-26-modules-101.markdown
1. The publish date was in the past, change to today.
2. Line endings were `[space][space][carriage return]` which created new lines. The Markdown flavour used in Jekyll needs lines ending in just `[carriage return]` to flow lines together into paragraphs. This corrects that.
n/a
=> fixes line endings, publish date on Modules 101

sass/_valkey.scss
**Fixes the Zola version, though the CSS should also work for the Jekyll version.**
The website behaves pretty well on mobile screen sizes except for the nav which breaks the site currently:
This PR adds some media queries to move the nav menu underneath the logo. In the event of a user having an even smaller screen, it will switch the menu to display in column format. (Not ideal but as the design of the site evolves, I imagine there'll be a niftier solution such as a burger etc etc.)
Fixed:
=> Fixes nav to be responsive on mobile screens

build/init-topics.sh, config.toml, content/commands/_index.md, templates/docs-page.html, templates/macros/docs.html
A few issues came up while reviewing for publication. valkey-io/valkey-doc#91
1. the regex was a little greedy and would occasionally eat two markdown links in one and causing a weird edge case where two transforms occur at once. The changes in `templates/macros/docs.html` fixes resolves this.
2. The docs repo differs in structure compared to website and calling commands is tricky. This gives an alias to the command listing page to make them play nice.
**Update 05/31** (probably should have made the original PR a draft) 
- Added a few more fixes for the URL re-writer
- Add the bits to allow for suppressing pages that still exist in the docs repo but shouldn't be published (yet/ever).
- Added the specific pages that need the review warning and to be supressed
n/a
By submitting this pull …
=> Fixes from topic review

sass/_valkey.scss
The YouTube embed in /docs/topics/ldb/ currently breaks the layout on the page when viewed on mobile devices.
PR adds a media query to set the embed width to 100% of the available area on small screens.
#76 
=> Fixes YouTube embed in /docs/topics/ldb/ breaking layout

sass/_valkey.scss
Fixes bug in layout that breaks YouTube boxes in mobile displays. 
n/a
=> Move to Prod: YouTube layout fix

.github/workflows/zola-deploy.yml
Adds fixes to build and deploy including exclusion of  themes and using `actions/deploy-pages@v4` instead of gh-pages branch
n/a
=> adds missing options build

content/blog/2024-05-24-may-roundup.md
The post "[What's new in Valkey for May 2024](https://github.com/valkey-io/valkey-io.github.io/blob/jekyll-version/_posts/2024-05-24-may-roundup.markdown)" didn't make it over from the transition from Jekyll to Zola. This PR restores the blog post.
n/a
=> restores may roundup blog post

.gitignore
For those transitioning from the Jekyll version to Zola, this adds the Jekyll build (`_site`) to the .gitignore file so it doesn't try to commit built files when switching between versions.
`_site` is unused in Zola.
n/a
=> adds _site to gitignore for transition purposes

config.toml, content/blog/2024-04-12-hello-world.md, content/blog/2024-04-16-valkey-7-2-5-out.md, content/blog/2024-04-26-modules-101.md, content/blog/2024-05-24-may-roundup.md, content/download/releases/v7-2-5.md, templates/blog-page.html, templates/includes/head.html
This release `atom.xml` adds a feed to valkey.io
Three things were needed & accomplished in this PR
1. `generate_feed` was set to `true`
2. The blog metadata needed to be reconfigured moving the `authors` array out from under `extra` back up to top-level of the meta data object. I had to touch all the blog posts to fix this and make a minor change the page template.
3. Add the feed auto discovery tag to the page header
To my pleasant surprise Zola was smart enough to find _any_ page with a date and add it to the feed. Since releases are technically pages with dates, they are also included in the feed, not just blog posts. I imagine this will be very useful for folks. Because releases don't really have any content, the resulting atom entry was a bit mysterious. Consequently, I added a …
=> adds `atom.xml` feed, simplifies authors metadata, adds description for release

.github/workflows/zola-deploy.yml
In https://github.com/valkey-io/valkey-io.github.io/commit/0ab9347c345327f58e5b22cdeb23f97928d38433, we moved to `generate_feeds`, which was only introduced in zola 19. Since this will be the default version folks install, move the deploy to zola 19 as well. See https://github.com/getzola/zola/releases/tag/v0.19.0 for release notes.
I didn't find anything else that seemed to be broken when doing the update.
Closes https://github.com/valkey-io/valkey-io.github.io/issues/103.
=> Move to zola 19 for deploy

templates/includes/head.html
Adding Fathom Analytics to site
Apparently I was supposed to do this when the site was first stood up but, as an unfunded project, LF didn't mention anything about it and I was more focused on getting a working site up.
Analytics are important as we make changes and add content to the site. The data will enable us to find what pages perform well vs. those that don't. It can also enable discovery of how users use the site itself, which docs are more important to users, and a bevy of other useful data as the project grows.
N/A
=> Adding analytics to valkey.io

config.toml, sass/_valkey.scss, templates/default.html
- Adds a top banner to the site on every page that is configurable by changing the `config.toml` file. If the configuration item is absent, the banner disappears
- Adds a message about Valkey Developer Day (to be removed the day before the event)
n/a
=> Adds the ability to add a top banner

content/download/releases/v7-2-5.md, content/download/releases/v7-2-6.md
Update the CDN links with the new subdomain ` download.valkey.io`
Try downloading using this link: https://download.valkey.io/releases/valkey-7.2.6-focal-arm64.tar.gz
```
> nslookup download.valkey.io
Non-authoritative answer:
download.valkey.io	canonical name = d307a34p6mmcbn.cloudfront.net.
```
No github issue was created.
=> Update the CDN links for binaries with the new subdomain `download.valkey.io`

content/blog/2024-09-13-unlock-one-million-rps-part2.md
The filename date and frontmatter date didn't match (each other) or the actual intended publish date.
n/a
=> fix the filename and meta data for correct pub date for 1 million RPS blog (Part 2)

content/download/releases/_index.md, content/download/releases/v8-0-0.md, templates/download.html, templates/includes/release.html, templates/release-section.html
This adds 
- a stub for Valkey 8 GA release 
- The ability to access previous releases via `/download/releases/`
NOTE: This is draft until ready for release.
(Each release as a permalink with download info - these already exist today: e.g. https://valkey.io/download/releases/v7-2-5/ )
=> Valkey 8 downloads

config.toml
valkey-io/valkey-doc#153 makes several items on the review list no longer needed. This PR removes them from the review list and consequently removes the rendered warning.
#94 
=> removes topics from review list

templates/default.html
- Move blog to a dedicated menu item at top level, so people can much easier find it (also it's not really "community", its just a blog)
- Under Community I now also added 'Connect'
- Open Github.com link in new tab
=> Improve header menu blog + connect

.gitignore, build/init-commands.sh, sass/_valkey.scss, templates/commands.html
This PR categorizes all commands in their `group` from the Valkey command JSON metadata files.
- Pulls in the `groups.json` file from valkey-doc
- Updates the template to list commands by category, use descriptions of each category from `groups.json`, add a quick index on the sidebar (as well as an alphabetical index on the sidebar) and switch to the right-aside from full width
- Adds styles for new template
It looks like this:
#150
=> adds categorization for commands

content/docs/index.md, sass/_valkey.scss, templates/block-menu.html, templates/commands.html, templates/default.html, templates/docs-page.html, templates/docs.html
This supersedes PR #87
This PR puts documentation in to categories, alters the top nav to make a single documentation drop down, and normalizes the heading in the documentation pages.
n/a
=> organizes documentation topics, normalizes docs headings

templates/macros/command.html, templates/macros/docs.html
In looking into #139, I ran the site through a site-wide link checker and came across a few corner cases the link rewriter didn't catch.
Before this change [filiph/linkcheck](https://github.com/filiph/linkcheck), resulted in the following final output:
```
Stats:
8786 links
216 destination URLs
604 URLs ignored
72 warnings
17 errors
```
After this change, the same script outputs:
```
Stats:
8818 links
203 destination URLs
611 URLs ignored
72 warnings
3 errors
```
The 3 remaining errors are related to known issues: missing`/clients/` and `/modules/` (the warnings are largely from `/topics/protocol` missing anchors, which is also known).
#139 
=> Link rewriter update

config.toml
The banner for Valkey 8 has been up for more than a month. This PR removes the notice banner. 
n/a
=> Remove valkey 8 notice banner (up for 1+ month)

templates/command-page.html, templates/docs-page.html
In an effort to encourage more folks to update the docs, created a button to easily navigate to the valkey-doc repo to update a page. If you click on it, it will take you to your fork (if you have one), allow you to edit and commit it in place, and the submit the PR. This seems like a very easy flow to get people to contribute.
My personal sadness.
I also originally attached an svg of the github icon, but it felt a bit silly.
=> Add quicklink to the github page to make edits

build/init-commands.sh
I got feedback that some people were getting 404 when they used valkey.io because they copy/pasted upper case commands into the URL.
This adds an uppercase alias to the website so `/command/GET/` forwards to `/command/get/`
n/a
=> allows for `/command/GET/` alongside `/command/get/`

content/blog/2024-09-13-unlock-one-million-rps-part2.md
I'm assuming pinning 3 IRQs to CPU 12 and 5 IRQs to CPU 13 is not what was intended here.
This patch fixes what I assume was a typo in this blog post.
=> Fix IRQ ranges

config.toml
Removes publishing hold on the protocol documentation after fixes in valkey-io/valkey-doc#197
n/a
=> remove publish hold on protocol docs

.gitignore, build/init-commands.sh, templates/command-page.html
They are built from `resp2_replies.json`/`resp3_replies.json` from valkey-doc. If the RESP2/RESP3 replies are equal, only a single section is added.
Closes #185 
=> Add reply sections to command pages

templates/macros/command.html
In the command page's "Usage:", the lower case `name` was used in case of a `pure-token`. However, the all caps `token` should be used instead. For MIGRATE, this makes an even bigger difference (see `empty-string`):
Before:
```
Usage:
MIGRATE host port 〈 key | empty-string 〉 destination-db timeout [ copy ] [ replace ] [ AUTH auth | AUTH2 username password ] [ KEYS keys ] [ [ KEYS keys ] ... ]
```
Now:
```
Usage:
MIGRATE host port 〈 key | "" 〉 destination-db timeout [ COPY ] [ REPLACE ] [ AUTH auth | AUTH2 username password ] [ KEYS keys ] [ [ KEYS keys ] ... ]
```
This addresses a part of #116
=> Use all caps pure-tokens in command "Usage:"

templates/macros/command.html
The `fix_links` macro handles markdown strings which do not need HTML escaping. Declaring its template expansion as "safe" prevents double quoting in input like "`<code>`".
This fixes problems when rendering the reply documentation of `CLUSTER INFO`, `GEORADIUS`, and `INFO`.
=> Command pages: Fix the `fix_links` macro

content/connect.md, content/slack.md
Our slack was not publicly visible, and I'm not convinced the link will be permanent. So add a redirect link on our page that you can use to join the slack that will be permanent. 
Hopefully addresses https://github.com/valkey-io/valkey-io.github.io/issues/198.
=> Add a permanent link for slack

content/download/releases/v7-2-5.md, content/download/releases/v7-2-6.md, content/download/releases/v7-2-7.md, content/download/releases/v7-2-8.md, content/download/releases/v8-0-0.md, content/download/releases/v8-0-1.md, content/download/releases/v8-0-2.md
Adds links to more artifacts that were build for valkey for ubuntu 22 and 24
Crosschecked all the binaries that are present on the production S3 bucket for artifacts.
closes #206 
=> Add more artifacts on the downloads page

.github/workflows/zola-deploy.yml
Automatically deploy the website when we update main, instead of having to merge it to Zola.
No issue, but discussed it offline.
=> Automatically deploy website on updates to main

templates/download.html, templates/release-section.html
For 8.0, we didn't have the release candidates on the release page, which I think was a miss. This new version now shows each major/minor pair on the all releases page and in addition also only shows the non-rc candidate versions on the downloads page.
=> Skip release candidates when on downloads page

.github/workflows/zola-deploy.yml
Allows someone with sufficient permissions to deploy the website by issuing a dispatch event to this repository. This is needed to allow other repository pushes to update the website.
=> Add a deploy dispatch event

templates/commands.html
- Added a search box for filtering commands dynamically.
- Implemented JavaScript for search functionality.
- Styled the search input for better UX.
Enhances usability by allowing users to quickly locate commands.
Added this:
https://github.com/valkey-io/valkey-io.github.io/issues/215
=> Add command search to the command reference page

content/blog/2025-03-28-new-hash-table/index.md, content/blog/2025-04-02-valkey-8-1-0-ga.md
=> Fixes to the blog posts about 8.1.0 release and hash table

content/download/releases/v8-0-0.md, content/download/releases/v8-0-1.md, content/download/releases/v8-0-2.md, content/download/releases/v8-1-0.md, templates/valkey-website-template.md
downloads page did not show the correct version which were available.
Also corrects the template that will be used by the automation.
We are discontinuing the focal support as it s EOL
> Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
=> Correct versions on download page and template correction

sass/_valkey.scss
The documentation tiles on the homepage were stacking awkwardly at screen widths between 768px and 1090px. Modified the grid layout to create a more natural 2x2 layout at these intermediate screen sizes, ensuring consistent spacing and better visual organization.
=> Bug fix: improve responsive layout of homepage documentation tiles

templates/command-page.html
This will add a section underneath the since on command pages to include ACL categories. This will add an @ in front of each category a comma inbetween and will set as lowercase.
As mentioned in the issue, non module commands only have their data type in the ACL categories. If this is a blocking issue I can see about adding all acl categories to the command pages for commands
This is based off of https://github.com/valkey-io/valkey-doc/issues/272 
=> Adding an ACL section for each command on their command page

sass/_valkey.scss, templates/commands.html, templates/left-aside.html
feat: restyle Commands Page with new layout and search functionality
- Add left sidebar with command categories and alphabetical list
- Implement responsive design with mobile-first approach
- Add search functionality with real-time filtering
- Style command groups with improved readability
- Add no-results message for empty searches
=> feat: restyle Commands Page with new layout and search functionality

templates/command-page.html
Currently implicit categories aren't shown on the website. This pr parses the command flags and adds the implicit categories based on this
Example images
If more screenshots are needed I can add to display all categories.
This will fully finish https://github.com/valkey-io/valkey-doc/issues/272#issuecomment-2864287464
=> Adding implicit ACL categories to be displayed on website

templates/default.html
Fix Github icon not loaded properly on footer
The icon is named `IconGithub.svg` but on the footer element is used as `IconGitHub.svg`
Closes #270 
=> fix: changes github icon file name displayed on footer

sass/_valkey.scss
Bug fix: standardize page content width alignment with header
The width-limiter class was inconsistently applied across pages, causing some content to align differently than the header. This change ensures all pages maintain consistent width and alignment with the header.
Fixes #266
=> Bug fix: standardize page content width alignment with header

content/blog/2025-04-09-introducing-bloom-filters.md
This change will fix the link in the blog to not point to the archived docker but the correct page. The current link takes you to an archived page
=> Updating extensions link to go to correct docker page

.gitignore
If building from the instructions in the readme, the generated directory `build-bloom-command-json` and `build-search-command-json` isn't ignored by git. This PR properly adds it to `.gitignore`
n/a
=> Adds bloom/search commands to gitignore

templates/client-list.html
Currently building the zola site locally is not possible when the clients directory is not built, as the `zola serve` command fails.
This is fixed by introducing an additional boolean variable `clients_built` in the client's page frontmatter, which is set to false by default, but updates to be true when running the `init_topics_and_clients.sh` script successfully. The page loads only if this var is set to true, otherwise a "Clients page not found" message is displayed, similar to the behavior in the commands and topics documentation.
=> Bug fix: allow local builds without requiring client directory

content/blog/2025-04-09-introducing-bloom-filters.md
Fixing the docker link as this has been updated again 
=> Fixing extensions link again after rename

content/try-valkey/index.md, templates/default.html, templates/valkey-try-me.html
This PR implements a browser-based environment that allows users to interact with Valkey-CLI commands without needing local installation. This feature was initially introduced in [Issue #1412](https://github.com/valkey-io/valkey/issues/1412), and it aims to provide a lightweight, easy-to-access platform for users to explore Valkey’s functionalities directly in the browser.
The solution uses a virtualized environment powered by [v86](https://github.com/copy/v86), a tool that emulates an x86-compatible CPU and hardware. The machine code for the environment is translated into WebAssembly modules at runtime, allowing it to run entirely within the browser.
* VM Configuration: When the page is loaded, the VM loads a preconfigured Alpine Linux image that already has the Valkey server and CLI …
=> added Try Valkey support

templates/default.html
It seems that when we merged try-my valkey we had a conflict where we duplicated some banner fields. This is just removing them.
No
=> Remove duplicate communnity and participants

content/blog/2025-03-4-go-client-in-public-preview.md, content/blog/2025-06-23-valkey-bundle-one-stop-shop-for-low-latency-modern-applications/index.md
- A couple of blog posts had issues with code highlighting which was spamming the Zola log making it hard to find issues.
- I also assigned code block names to undefined ones to stop the linter yelling at me
n/a
=> Fixing code highlighting issues

sass/_valkey.scss, static/assets/js/nav.js, static/img/icon-outline-close.svg, templates/default.html
feat(ui): Restyle top navigation bar and banner
- Add banner close functionality with 24-hour persistence
=> feat(ui): Restyle top navigation bar and banner

.github/workflows/zola-deploy.yml
The previous workflow was just using the current repositories, which worked when I was testing but didn't work for actual PRs.
No Issue
=> Correctly set the source repository when doing PR validation

content/command-list/_index.md, templates/command-list.html, templates/command-page.html
When the side bar was added to the command page it caused a massive increase in build times (see #321). This was caused by each command page needing to pull every command JSON file into to generate the list.
This PR takes a different approach, it adds a page (`/command-list/`), that is generated once, which contains the all the commands formatted as list items. Then, on each command page, it pulls that content in with some simple javascript. 
Full build times were previously taking 40-70 seconds. After this change, the build times are taking approximately 1.2 seconds.
```
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 564 pages (0 orphan) and 8 sections
Warning: Highlight language plaintext not found
Done in …
```
=> generate once, load many

templates/command-page.html
There is a lot of confusion about the meaning of deprecation in Valkey and there is an effort to formally un-deprecate a number of commands (See #[2459](https://github.com/valkey-io/valkey/issues/2459)). As such, this PR removes the "Deprecated" notice for the commands under reconsideration.
n/a
=> remove deprecation notice due to the great un-deprecation

templates/macros/command.html
Fix broken links from command pages to other command pages.
Example: The link to DEL on the page https://valkey.io/commands/unlink/
Without this PR, the link points to https://valkey.io/commands/unlink/del.md which doesn't exist.
With this PR, the link points to the correct page https://valkey.io/commands/del/
Fixes #351
=> Fix command-to-command links

templates/includes/head.html
There was a merge issue in https://github.com/valkey-io/valkey-io.github.io/pull/345/files, where fathom was re-added, just removing it again.
N/A
=> Remove Fathom again

content/community/_index.md, templates/community.html
(exactly the same as #364 but based on commit 4888f10... for whatever reason GitHub _did not_ like the combinations of changes - it was far easier to just manually move these changes over top of 4888f10 and do another PR)
This PR refactors the /community/ page into a section. It allows us to add unique landing page variations of the community page.
For example, if you add an markdown file to /content/community/ this will create a new URL under /community/.
This is especially useful for events where we may want to direct attendees to a specific set of resources for that event. For example, I could send PyConAfrica attendees to a vakey.io/community/pycon-africa via a QR code. On this specific landing page it would contain information about demos and/or slides relevant to the event along …
=> Community event landing page 
